version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64
configuration: Release

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
  - IF NOT EXIST C:\ProgramData\chocolatey\bin\swig.exe choco install tools\windows\swig.3.0.12.nupkg --yes --limit-output #> $null

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - curl -o mkn.exe -L https://ci.appveyor.com/api/projects/dekken/maiken/artifacts/bin/build/mkn.exe
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - SET MKN_CL_PREFERRED=1
  - C:\Swig6-x64\Scripts\pip install numpy
  - bash -c "PATH=\"$PWD:/c/Swig6-x64/:/c/Program Files/Git/usr/bin:$PATH\"; KLOG=3 ./mkn clean build -dtO"
  - bash -c "PATH=\"$PWD:/c/Swig6-x64/:/c/Program Files/Git/usr/bin:$PATH\"; KLOG=3 ./mkn clean build -tOp test run"
