name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MKN_LIB_LINK_LIB: 1
  MKN_KUL_GIT_CO: --depth 1

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_arm_osx
        chmod +x mkn
        KLOG=2 ./mkn clean build run -dtOa "-std=c++20 -fPIC"

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - shell: cmd
      run: | # /bin/link interferes with cl/link.exe
        bash -c "rm /bin/link"
        bash -c 'curl -Lo mkn.exe https://github.com/mkn/mkn/releases/download/latest/mkn.exe'
        SET KLOG=2
        mkn clean build run -dtOa "-EHsc -std:c++20"
