name: windows-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    # setup MSVC compiler
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - env:
        KUL_GIT_CO: --depth 1
        MKN_CL_PREFERRED: 1
      shell: cmd
      run: | # /bin/link interferes with cl/link.exe
        bash -c "rm /bin/link"
        bash -c 'curl -Lo mkn.exe https://github.com/mkn/mkn/releases/download/latest/mkn.exe'
        bash -c 'KLOG=2 ./mkn clean build run -dtOa "-EHsc -std:c++17"'
